# Takes medium resolution file generated by https://geojson-maps.kyd.com.au/
# Medium resolution is used because some countries in the large version are
# missing iso codes.
import json
with open("world-med-orig.geo.json") as f:
    world = json.load(f)
    out_features = []
    for country_feature in world['features']:
        country_feature['properties'] = {
            'ISO2': country_feature['properties']['iso_a2'],
            'name': country_feature['properties']['name']
        }
        out_features.append(country_feature)
    world['features'] = out_features
with open("world.geo.json", "w") as f:
    json.dump(world, f)
